/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mpe_config.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4498aae3385f5af8744a6e4f814866c8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mpe/mpe_config.h>
// pydoc.h is automatically generated in the build directory
#include <mpe_config_pydoc.h>

void bind_mpe_config(py::module& m)
{


    py::enum_<::gr::mpe::mpe_ping_reply_t>(m,"mpe_ping_reply_t")
        .value("PING_REPLY_OFF", ::gr::mpe::mpe_ping_reply_t::PING_REPLY_OFF) // 0
        .value("PING_REPLY_ON", ::gr::mpe::mpe_ping_reply_t::PING_REPLY_ON) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::mpe::mpe_ping_reply_t>();
    py::enum_<::gr::mpe::mpe_ipaddr_spoof_t>(m,"mpe_ipaddr_spoof_t")
        .value("IPADDR_SPOOF_OFF", ::gr::mpe::mpe_ipaddr_spoof_t::IPADDR_SPOOF_OFF) // 0
        .value("IPADDR_SPOOF_ON", ::gr::mpe::mpe_ipaddr_spoof_t::IPADDR_SPOOF_ON) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::mpe::mpe_ipaddr_spoof_t>();



}








