/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mpe_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0d5b1d6f3ba6642bf056a770de7aa243)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mpe/mpe_source.h>
// pydoc.h is automatically generated in the build directory
#include <mpe_source_pydoc.h>

void bind_mpe_source(py::module& m)
{

    using mpe_source    = ::gr::mpe::mpe_source;


    py::class_<mpe_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<mpe_source>>(m, "mpe_source", D(mpe_source))

        .def(py::init(&mpe_source::make),
           py::arg("mac_address"),
           py::arg("ping_reply"),
           py::arg("ipaddr_spoof"),
           py::arg("src_address"),
           py::arg("dst_address"),
           D(mpe_source,make)
        )
        



        ;




}








